Update README for 5.7
andreasindal/laravel-markdown pull request #34
Opened 2018-12-30 01:38 UTC by thomaspatricksteven

2019-01-17 09:55 UTC, juliano-barros requested changes
Good idea, It was hard for me to find out there was a new version for the new version of Laravel. Although everything is fine I'd like to suggest a slight change.

2019-01-17 09:55 UTC, juliano-barros commented on README.md
> +| 5.7             | [3.0.1](https://github.com/andreasindal/laravel-markdown/tree/master) |
```suggestion
| 5.7             | [3.0.1](https://github.com/andreasindal/laravel-markdown/tree/3.0.1) |
```

2019-01-17 14:03 UTC, andreasindal commented
Hi! Thanks for your submission. I'm sorry that it has taken me so long to respond. If you make the change according to @juliano-barros suggestion I'll merge it tonight. Thank you!

2019-02-24 20:32 UTC, thomaspatricksteven commented
@andreasindal Sorry, I didn't see you had replied. Changes merged in.

2019-02-24 20:57 UTC, andreasindal commented
Awesome, thank you for your contribution! 🎉✨

2019-02-24 20:58 UTC, merged